basePath: /api/v1
definitions:
  rest.AccessToken:
    properties:
      access_token:
        type: string
    required:
    - access_token
    type: object
  rest.Auth:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  rest.Claims:
    properties:
      employee_id:
        type: string
      roles:
        items:
          type: string
        type: array
    type: object
  rest.CreateUserRequest:
    properties:
      employee_id:
        type: string
      username:
        type: string
    required:
    - username
    type: object
  rest.CreateUserResponse:
    properties:
      id:
        type: string
    type: object
  rest.HTTPError:
    properties:
      error:
        example: status bad request
        type: string
    type: object
  rest.HTTPResponse:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: a message
        type: string
    type: object
  rest.JWT:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      id_token:
        type: string
      not_before_policy:
        type: integer
      refresh_expires_in:
        type: integer
      refresh_token:
        type: string
      scope:
        type: string
      session_state:
        type: string
      token_type:
        type: string
    type: object
  rest.RefreshToken:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  rest.SetPasswordRequest:
    properties:
      password:
        type: string
      temporary:
        type: boolean
    required:
    - password
    type: object
info:
  contact:
    email: contato@coding4u.com.br
    name: Coding4u
  description: Swagger API for Golang Project Auth.
  termsOfService: http://swagger.io/terms/
  title: Auth Swagger API
  version: "1.0"
paths:
  /auth/claims:
    post:
      consumes:
      - application/json
      description: Get Claims by access token
      operationId: findClaimsByToken
      parameters:
      - description: JSON body for get claims
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.AccessToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.Claims'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.HTTPError'
      summary: get claims
      tags:
      - Auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: System authentication
      operationId: login
      parameters:
      - description: JSON body for authentication
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.Auth'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.JWT'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/rest.HTTPError'
      summary: log in
      tags:
      - Auth
  /auth/refresh-token:
    post:
      consumes:
      - application/json
      description: Refresh token route
      operationId: refreshToken
      parameters:
      - description: JSON body for refresh token
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.RefreshToken'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.JWT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPError'
      summary: refresh token
      tags:
      - Auth
  /user:
    post:
      consumes:
      - application/json
      description: Create User
      operationId: createUser
      parameters:
      - description: JSON body for create user
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.CreateUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.HTTPError'
      summary: create User
      tags:
      - User
  /user/{id}/password:
    post:
      consumes:
      - application/json
      description: Set user password
      operationId: setPassword
      parameters:
      - description: JSON body set user password
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/rest.SetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/rest.HTTPResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/rest.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/rest.HTTPError'
      summary: create User
      tags:
      - User
swagger: "2.0"
