syntax = "proto3";

package github.com.c_4u;

option go_package = "/protofiles;pb";

message LoginRequest {
    string username = 1;
    string password = 2;
}

message RefreshTokenRequest {
    string refresh_token = 1;
}

message FindClaimsByTokenRequest {
    string access_token = 1;
}

message JWT {
    string access_token = 1;
    string id_token = 2;
    int64 expires_in = 3;
    int64 refresh_expires_in = 4;
    string refresh_token = 5;
    string token_type = 6;
    int64 not_before_policy = 7;
    string session_state = 8;
    string scope = 9;
}

message Claims {
    string employee_id = 1;
    repeated string roles = 2;
}

message CreateUserRequest {
    User user = 1;
    string access_token = 2;
}

message CreateUserResponse {
    string id = 1;
}

message User {
    string id = 1;
    string username = 2;
    string first_name = 3;
    string last_name = 4;
    string email = 5;
    bool enabled = 6;
    bool email_verified = 7;
    string employee_id = 8;
}

message SetPasswordRequest {
    string user_id = 1;
    string password = 2;
    bool temporary = 3;
    string access_token = 4;
}

message StatusResponse {
    uint32 code = 1;
    string message = 2;
    string error = 3;
}

service AuthKeycloakAcl {
    rpc Login (LoginRequest) returns (JWT);
    rpc RefreshToken (RefreshTokenRequest) returns (JWT);
    rpc FindClaimsByToken (FindClaimsByTokenRequest) returns (Claims);
    rpc CreateUser (CreateUserRequest) returns (CreateUserResponse);
    rpc SetPassword (SetPasswordRequest) returns (StatusResponse);
}
