// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthKeycloakAclClient is the client API for AuthKeycloakAcl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthKeycloakAclClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*JWT, error)
	RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*JWT, error)
	FindClaimsByToken(ctx context.Context, in *FindClaimsByTokenRequest, opts ...grpc.CallOption) (*Claims, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type authKeycloakAclClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthKeycloakAclClient(cc grpc.ClientConnInterface) AuthKeycloakAclClient {
	return &authKeycloakAclClient{cc}
}

func (c *authKeycloakAclClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*JWT, error) {
	out := new(JWT)
	err := c.cc.Invoke(ctx, "/github.com.c_4u.AuthKeycloakAcl/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authKeycloakAclClient) RefreshToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*JWT, error) {
	out := new(JWT)
	err := c.cc.Invoke(ctx, "/github.com.c_4u.AuthKeycloakAcl/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authKeycloakAclClient) FindClaimsByToken(ctx context.Context, in *FindClaimsByTokenRequest, opts ...grpc.CallOption) (*Claims, error) {
	out := new(Claims)
	err := c.cc.Invoke(ctx, "/github.com.c_4u.AuthKeycloakAcl/FindClaimsByToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authKeycloakAclClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/github.com.c_4u.AuthKeycloakAcl/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authKeycloakAclClient) SetPassword(ctx context.Context, in *SetPasswordRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/github.com.c_4u.AuthKeycloakAcl/SetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthKeycloakAclServer is the server API for AuthKeycloakAcl service.
// All implementations must embed UnimplementedAuthKeycloakAclServer
// for forward compatibility
type AuthKeycloakAclServer interface {
	Login(context.Context, *LoginRequest) (*JWT, error)
	RefreshToken(context.Context, *RefreshTokenRequest) (*JWT, error)
	FindClaimsByToken(context.Context, *FindClaimsByTokenRequest) (*Claims, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	SetPassword(context.Context, *SetPasswordRequest) (*StatusResponse, error)
	mustEmbedUnimplementedAuthKeycloakAclServer()
}

// UnimplementedAuthKeycloakAclServer must be embedded to have forward compatible implementations.
type UnimplementedAuthKeycloakAclServer struct {
}

func (UnimplementedAuthKeycloakAclServer) Login(context.Context, *LoginRequest) (*JWT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthKeycloakAclServer) RefreshToken(context.Context, *RefreshTokenRequest) (*JWT, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (UnimplementedAuthKeycloakAclServer) FindClaimsByToken(context.Context, *FindClaimsByTokenRequest) (*Claims, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindClaimsByToken not implemented")
}
func (UnimplementedAuthKeycloakAclServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedAuthKeycloakAclServer) SetPassword(context.Context, *SetPasswordRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPassword not implemented")
}
func (UnimplementedAuthKeycloakAclServer) mustEmbedUnimplementedAuthKeycloakAclServer() {}

// UnsafeAuthKeycloakAclServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthKeycloakAclServer will
// result in compilation errors.
type UnsafeAuthKeycloakAclServer interface {
	mustEmbedUnimplementedAuthKeycloakAclServer()
}

func RegisterAuthKeycloakAclServer(s grpc.ServiceRegistrar, srv AuthKeycloakAclServer) {
	s.RegisterService(&AuthKeycloakAcl_ServiceDesc, srv)
}

func _AuthKeycloakAcl_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthKeycloakAclServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.c_4u.AuthKeycloakAcl/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthKeycloakAclServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthKeycloakAcl_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthKeycloakAclServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.c_4u.AuthKeycloakAcl/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthKeycloakAclServer).RefreshToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthKeycloakAcl_FindClaimsByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindClaimsByTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthKeycloakAclServer).FindClaimsByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.c_4u.AuthKeycloakAcl/FindClaimsByToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthKeycloakAclServer).FindClaimsByToken(ctx, req.(*FindClaimsByTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthKeycloakAcl_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthKeycloakAclServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.c_4u.AuthKeycloakAcl/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthKeycloakAclServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthKeycloakAcl_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthKeycloakAclServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.c_4u.AuthKeycloakAcl/SetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthKeycloakAclServer).SetPassword(ctx, req.(*SetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthKeycloakAcl_ServiceDesc is the grpc.ServiceDesc for AuthKeycloakAcl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthKeycloakAcl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.c_4u.AuthKeycloakAcl",
	HandlerType: (*AuthKeycloakAclServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthKeycloakAcl_Login_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _AuthKeycloakAcl_RefreshToken_Handler,
		},
		{
			MethodName: "FindClaimsByToken",
			Handler:    _AuthKeycloakAcl_FindClaimsByToken_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _AuthKeycloakAcl_CreateUser_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _AuthKeycloakAcl_SetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth.proto",
}
